# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];

  users.users.poisonphang = {
    uid = 501;
    extraGroups = [ "wheel" "docker" ];

    createHome = true;
    group = "users";
    home = "/home/poisonphang";
    homeMode = "700";
    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    shell = pkgs.zsh;
    useDefaultShell = true;
  };

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  environment = {
    systemPackages = with pkgs; [
      bat
      bottom
      delta
      eza
      fd 
      file
      fzf
      git
      git-lfs
      gnumake
      gnupg
      helix
      ltex-ls
      nil
      ssh-to-pgp
      xclip
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "America/Chicago";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  system.stateVersion = "24.05"; # Did you read the comment?
}
